/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'latitude' : IDL.Float64,
  'city' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const CartItem = IDL.Record({
  'restaurantId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const FoodOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'createdAt' : Time,
  'restaurantId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'isApproved' : IDL.Bool,
  'ownerId' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveRestaurant' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createRestaurant' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getMenuItemsByRestaurant' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrdersByCustomer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FoodOrder)],
      ['query'],
    ),
  'getOrdersByRestaurant' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FoodOrder)],
      ['query'],
    ),
  'getRestaurant' : IDL.Func([IDL.Nat], [Restaurant], ['query']),
  'getRestaurantsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRestaurants' : IDL.Func([IDL.Bool], [IDL.Vec(Restaurant)], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, DeliveryAddress], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateRestaurantStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'latitude' : IDL.Float64,
    'city' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const CartItem = IDL.Record({
    'restaurantId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const FoodOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'createdAt' : Time,
    'restaurantId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'isApproved' : IDL.Bool,
    'ownerId' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveRestaurant' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'createRestaurant' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(FoodOrder)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getMenuItemsByRestaurant' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrdersByCustomer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FoodOrder)],
        ['query'],
      ),
    'getOrdersByRestaurant' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FoodOrder)],
        ['query'],
      ),
    'getRestaurant' : IDL.Func([IDL.Nat], [Restaurant], ['query']),
    'getRestaurantsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRestaurants' : IDL.Func([IDL.Bool], [IDL.Vec(Restaurant)], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, DeliveryAddress], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateRestaurantStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };