/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'restaurantId' : bigint,
  'quantity' : bigint,
  'menuItemId' : bigint,
}
export interface DeliveryAddress {
  'latitude' : number,
  'city' : string,
  'longitude' : number,
  'address' : string,
  'phone' : string,
}
export interface FoodOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'createdAt' : Time,
  'restaurantId' : bigint,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<CartItem>,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'restaurantId' : bigint,
  'category' : string,
  'price' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Restaurant {
  'id' : bigint,
  'latitude' : number,
  'isApproved' : boolean,
  'ownerId' : Principal,
  'city' : string,
  'name' : string,
  'cuisineType' : string,
  'description' : string,
  'isActive' : boolean,
  'longitude' : number,
  'address' : string,
  'phone' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'approveRestaurant' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string, boolean],
    bigint
  >,
  'createRestaurant' : ActorMethod<
    [string, string, string, string, string, string, number, number],
    bigint
  >,
  'getAllOrders' : ActorMethod<[], Array<FoodOrder>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMenuItem' : ActorMethod<[bigint], MenuItem>,
  'getMenuItemsByRestaurant' : ActorMethod<[bigint], Array<MenuItem>>,
  'getOrdersByCustomer' : ActorMethod<[Principal], Array<FoodOrder>>,
  'getOrdersByRestaurant' : ActorMethod<[bigint], Array<FoodOrder>>,
  'getRestaurant' : ActorMethod<[bigint], Restaurant>,
  'getRestaurantsByOwner' : ActorMethod<[Principal], Array<Restaurant>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listRestaurants' : ActorMethod<[boolean], Array<Restaurant>>,
  'placeOrder' : ActorMethod<[bigint, DeliveryAddress], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateRestaurantStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];